version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    ports:
      - "3000:3000"
    volumes:
      - shared_volume:/zap/wrk
      - /src/data/sast:/src/data/sast
      - /var/run/docker.sock:/var/run/docker.sock  # Permitir acesso ao Docker daemon
      - /src/data/mobile:/src/data/mobile
      - /src/data/dast:/src/data/dast
    networks:
      - services_scan
    privileged: true
    environment:
      - ZAP_PROXY_HOST=zaproxy
      - ZAP_PROXY_PORT=8080
      - JWT_SECRET=${TOKEN_UI}  # Defina o segredo do JWT aqui
    env_file:
      - .env  # Inclua o arquivo .env para que todas as variáveis de ambiente sejam carregadas

  # zaproxy:
  #   image: zaproxy/zap-stable
  #   container_name: dast_scan
  #   command: zap.sh -daemon -host 0.0.0.0 -port 8080 -config api.addrs.addr.name=.* -config api.addrs.addr.regex=true -config api.key=${ZAP_API_KEY}
  #   ports:
  #     - "8080:8080"
  #   user: zap
  #   environment:
  #     - ZAP_API_KEY=${ZAP_API_KEY}
  #   volumes:
  #     - shared_volume:/zap/wrk
  #     - shared_volume:/src/data/dast
  #   networks:
  #     - services_scan

  # mobsf:
  #   image: opensecurity/mobile-security-framework-mobsf
  #   container_name: mobile_scan
  #   ports:
  #     - "8081:8000"
  #   volumes:
  #     - shared_volume:/src/data/mobile
  #   networks:
  #     - services_scan

volumes:
  shared_volume:

networks:
  services_scan:
    driver: bridge
